/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portunus;

/**
 *
 * @author sgoug
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form MainScreenMockUp
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginScreen = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        LoginPgBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NavigationScreen = new javax.swing.JPanel();
        BGPanel = new javax.swing.JPanel();
        NavMenu1 = new javax.swing.JPanel();
        PortunusLogo1 = new javax.swing.JLabel();
        PasswordsBtn = new javax.swing.JButton();
        SettingsBtn = new javax.swing.JButton();
        LoginOutBtn = new javax.swing.JButton();
        ChangingPanel = new javax.swing.JPanel();
        PasswordsPan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AccountList = new javax.swing.JList<>();
        AccDisplayPan = new javax.swing.JPanel();
        NewAccountPnl = new javax.swing.JPanel();
        NewAccNameField = new javax.swing.JTextField();
        NewAccNameLbl = new javax.swing.JLabel();
        NewAccUNField = new javax.swing.JTextField();
        NewAccUNLbl = new javax.swing.JLabel();
        NewAccPWField = new javax.swing.JTextField();
        NewAccPWLbl = new javax.swing.JLabel();
        AddAcountBtn = new javax.swing.JButton();
        NewAccSQLbl = new javax.swing.JLabel();
        NewAccSQField = new javax.swing.JTextField();
        ExistingAccountPnl = new javax.swing.JPanel();
        AccUNField = new javax.swing.JTextField();
        AccUNLbl = new javax.swing.JLabel();
        AccPWLbl = new javax.swing.JLabel();
        AccPWField = new javax.swing.JTextField();
        AccSQField = new javax.swing.JTextField();
        AccSQLbl = new javax.swing.JLabel();
        UNCopyBtn = new javax.swing.JButton();
        PWCopyBtn = new javax.swing.JButton();
        SQCopyBtn = new javax.swing.JButton();
        DeleteAccBtn = new javax.swing.JButton();
        EditAccbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ShowAccBtn = new javax.swing.JButton();
        SettingsPan = new javax.swing.JPanel();
        jColorChooser1 = new javax.swing.JColorChooser();
        ColorOptionsLabel = new javax.swing.JLabel();
        ColorOptionsLabel1 = new javax.swing.JLabel();
        FontSizeSelection = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.CardLayout());

        LoginScreen.setBackground(new java.awt.Color(153, 153, 153));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel3.setText("Password");

        LoginPgBtn.setBackground(new java.awt.Color(204, 204, 204));
        LoginPgBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        LoginPgBtn.setText("Login");
        LoginPgBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        LoginPgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPgBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel4.setText("Welcome to Portunus!");

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setText("Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(LoginPgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel4)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(LoginPgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout LoginScreenLayout = new javax.swing.GroupLayout(LoginScreen);
        LoginScreen.setLayout(LoginScreenLayout);
        LoginScreenLayout.setHorizontalGroup(
            LoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginScreenLayout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        LoginScreenLayout.setVerticalGroup(
            LoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginScreenLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        getContentPane().add(LoginScreen, "card3");

        NavigationScreen.setBackground(new java.awt.Color(153, 153, 153));
        NavigationScreen.setForeground(new java.awt.Color(153, 153, 153));
        NavigationScreen.setMaximumSize(new java.awt.Dimension(600, 900));

        BGPanel.setBackground(new java.awt.Color(153, 153, 153));

        NavMenu1.setBackground(new java.awt.Color(51, 204, 255));
        NavMenu1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        PortunusLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portunus/PortunusLogo15.png"))); // NOI18N

        PasswordsBtn.setBackground(new java.awt.Color(204, 204, 204));
        PasswordsBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        PasswordsBtn.setText("Passwords");
        PasswordsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        PasswordsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordsBtnActionPerformed(evt);
            }
        });

        SettingsBtn.setBackground(new java.awt.Color(204, 204, 204));
        SettingsBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        SettingsBtn.setText("Settings");
        SettingsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        SettingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsBtnActionPerformed(evt);
            }
        });

        LoginOutBtn.setBackground(new java.awt.Color(204, 204, 204));
        LoginOutBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        LoginOutBtn.setText("Log In/out");
        LoginOutBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        LoginOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavMenu1Layout = new javax.swing.GroupLayout(NavMenu1);
        NavMenu1.setLayout(NavMenu1Layout);
        NavMenu1Layout.setHorizontalGroup(
            NavMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavMenu1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(NavMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PasswordsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SettingsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoginOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PortunusLogo1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        NavMenu1Layout.setVerticalGroup(
            NavMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PortunusLogo1)
                .addGap(30, 30, 30)
                .addComponent(PasswordsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(SettingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(LoginOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ChangingPanel.setBackground(new java.awt.Color(153, 153, 153));
        ChangingPanel.setLayout(new java.awt.CardLayout());

        PasswordsPan.setBackground(new java.awt.Color(153, 153, 153));

        AccountList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        AccountList.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        AccountList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "New Account", "Existing Account" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        AccountList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(AccountList);

        AccDisplayPan.setBackground(new java.awt.Color(51, 204, 255));
        AccDisplayPan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        AccDisplayPan.setLayout(new java.awt.CardLayout());

        NewAccountPnl.setBackground(new java.awt.Color(51, 204, 255));
        NewAccountPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        NewAccNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        NewAccNameLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        NewAccNameLbl.setText("Account Name:");

        NewAccUNField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        NewAccUNLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        NewAccUNLbl.setText("Username:");

        NewAccPWField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        NewAccPWLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        NewAccPWLbl.setText("Password:");

        AddAcountBtn.setBackground(new java.awt.Color(204, 204, 204));
        AddAcountBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        AddAcountBtn.setText("Done!");
        AddAcountBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        NewAccSQLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        NewAccSQLbl.setText("Security Question:");

        NewAccSQField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout NewAccountPnlLayout = new javax.swing.GroupLayout(NewAccountPnl);
        NewAccountPnl.setLayout(NewAccountPnlLayout);
        NewAccountPnlLayout.setHorizontalGroup(
            NewAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewAccountPnlLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(NewAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewAccountPnlLayout.createSequentialGroup()
                        .addComponent(NewAccSQField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(AddAcountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NewAccountPnlLayout.createSequentialGroup()
                        .addGroup(NewAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewAccPWLbl)
                            .addGroup(NewAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NewAccUNLbl)
                                .addComponent(NewAccNameLbl)
                                .addComponent(NewAccNameField)
                                .addComponent(NewAccUNField)
                                .addComponent(NewAccPWField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NewAccSQLbl))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        NewAccountPnlLayout.setVerticalGroup(
            NewAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewAccountPnlLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(NewAccNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewAccNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NewAccUNLbl)
                .addGap(6, 6, 6)
                .addComponent(NewAccUNField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(NewAccPWLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewAccPWField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(NewAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewAccountPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddAcountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewAccountPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NewAccSQLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NewAccSQField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        AccDisplayPan.add(NewAccountPnl, "card2");

        ExistingAccountPnl.setBackground(new java.awt.Color(51, 204, 255));
        ExistingAccountPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        AccUNField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        AccUNLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        AccUNLbl.setText("Username:");

        AccPWLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        AccPWLbl.setText("Password:");

        AccPWField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        AccSQField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        AccSQLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        AccSQLbl.setText("Security Question:");

        UNCopyBtn.setBackground(new java.awt.Color(204, 204, 204));
        UNCopyBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        UNCopyBtn.setText("Copy");
        UNCopyBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        PWCopyBtn.setBackground(new java.awt.Color(204, 204, 204));
        PWCopyBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        PWCopyBtn.setText("Copy");
        PWCopyBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        SQCopyBtn.setBackground(new java.awt.Color(204, 204, 204));
        SQCopyBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        SQCopyBtn.setText("Copy");
        SQCopyBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        DeleteAccBtn.setBackground(new java.awt.Color(204, 204, 204));
        DeleteAccBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        DeleteAccBtn.setText("Delete");
        DeleteAccBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        EditAccbtn.setBackground(new java.awt.Color(204, 204, 204));
        EditAccbtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        EditAccbtn.setText("Edit");
        EditAccbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setText("Account Name");

        javax.swing.GroupLayout ExistingAccountPnlLayout = new javax.swing.GroupLayout(ExistingAccountPnl);
        ExistingAccountPnl.setLayout(ExistingAccountPnlLayout);
        ExistingAccountPnlLayout.setHorizontalGroup(
            ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExistingAccountPnlLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                        .addComponent(AccSQLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(UNCopyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PWCopyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SQCopyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                        .addGap(61, 61, 61)
                        .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeleteAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditAccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                        .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AccPWLbl)
                            .addComponent(AccUNLbl)
                            .addComponent(AccUNField, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(AccPWField)
                            .addComponent(AccSQField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(21, 21, 21))
        );
        ExistingAccountPnlLayout.setVerticalGroup(
            ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(AccUNLbl))
                    .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UNCopyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AccUNField, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(AccPWLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccPWField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PWCopyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(DeleteAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditAccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                        .addComponent(AccSQLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccSQField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SQCopyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        AccDisplayPan.add(ExistingAccountPnl, "card3");

        ShowAccBtn.setBackground(new java.awt.Color(204, 204, 204));
        ShowAccBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        ShowAccBtn.setText("Show");
        ShowAccBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout PasswordsPanLayout = new javax.swing.GroupLayout(PasswordsPan);
        PasswordsPan.setLayout(PasswordsPanLayout);
        PasswordsPanLayout.setHorizontalGroup(
            PasswordsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordsPanLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PasswordsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PasswordsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(AccDisplayPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ShowAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        PasswordsPanLayout.setVerticalGroup(
            PasswordsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordsPanLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowAccBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AccDisplayPan, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ChangingPanel.add(PasswordsPan, "card2");

        SettingsPan.setBackground(new java.awt.Color(153, 153, 153));

        ColorOptionsLabel.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        ColorOptionsLabel.setText("Change Color:");

        ColorOptionsLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        ColorOptionsLabel1.setText("Font Size:");

        FontSizeSelection.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        FontSizeSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Extra Small", "Small", "Normal", "Large", "Extra Large" }));

        javax.swing.GroupLayout SettingsPanLayout = new javax.swing.GroupLayout(SettingsPan);
        SettingsPan.setLayout(SettingsPanLayout);
        SettingsPanLayout.setHorizontalGroup(
            SettingsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsPanLayout.createSequentialGroup()
                .addGroup(SettingsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SettingsPanLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(ColorOptionsLabel))
                    .addGroup(SettingsPanLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(SettingsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SettingsPanLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(ColorOptionsLabel1))
                            .addComponent(FontSizeSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        SettingsPanLayout.setVerticalGroup(
            SettingsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingsPanLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ColorOptionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ColorOptionsLabel1)
                .addGap(18, 18, 18)
                .addComponent(FontSizeSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        ChangingPanel.add(SettingsPan, "card3");

        javax.swing.GroupLayout BGPanelLayout = new javax.swing.GroupLayout(BGPanel);
        BGPanel.setLayout(BGPanelLayout);
        BGPanelLayout.setHorizontalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NavMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChangingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BGPanelLayout.setVerticalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NavMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChangingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout NavigationScreenLayout = new javax.swing.GroupLayout(NavigationScreen);
        NavigationScreen.setLayout(NavigationScreenLayout);
        NavigationScreenLayout.setHorizontalGroup(
            NavigationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationScreenLayout.createSequentialGroup()
                .addComponent(BGPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        NavigationScreenLayout.setVerticalGroup(
            NavigationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(NavigationScreen, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordsBtnActionPerformed
        //cardLayout.show()
        PasswordsPan.setVisible(true);
        SettingsPan.setVisible(false);
    }//GEN-LAST:event_PasswordsBtnActionPerformed

    private void SettingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsBtnActionPerformed
        SettingsPan.setVisible(true);
        PasswordsPan.setVisible(false);
    }//GEN-LAST:event_SettingsBtnActionPerformed

    private void LoginPgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPgBtnActionPerformed
        NavigationScreen.setVisible(true);
        LoginScreen.setVisible(false);
    }//GEN-LAST:event_LoginPgBtnActionPerformed

    private void LoginOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginOutBtnActionPerformed
        LoginScreen.setVisible(true);
        NavigationScreen.setVisible(false);
    }//GEN-LAST:event_LoginOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccDisplayPan;
    private javax.swing.JTextField AccPWField;
    private javax.swing.JLabel AccPWLbl;
    private javax.swing.JTextField AccSQField;
    private javax.swing.JLabel AccSQLbl;
    private javax.swing.JTextField AccUNField;
    private javax.swing.JLabel AccUNLbl;
    private javax.swing.JList<String> AccountList;
    private javax.swing.JButton AddAcountBtn;
    private javax.swing.JPanel BGPanel;
    private javax.swing.JPanel ChangingPanel;
    private javax.swing.JLabel ColorOptionsLabel;
    private javax.swing.JLabel ColorOptionsLabel1;
    private javax.swing.JButton DeleteAccBtn;
    private javax.swing.JButton EditAccbtn;
    private javax.swing.JPanel ExistingAccountPnl;
    private javax.swing.JComboBox<String> FontSizeSelection;
    private javax.swing.JButton LoginOutBtn;
    private javax.swing.JButton LoginPgBtn;
    private javax.swing.JPanel LoginScreen;
    private javax.swing.JPanel NavMenu1;
    private javax.swing.JPanel NavigationScreen;
    private javax.swing.JTextField NewAccNameField;
    private javax.swing.JLabel NewAccNameLbl;
    private javax.swing.JTextField NewAccPWField;
    private javax.swing.JLabel NewAccPWLbl;
    private javax.swing.JTextField NewAccSQField;
    private javax.swing.JLabel NewAccSQLbl;
    private javax.swing.JTextField NewAccUNField;
    private javax.swing.JLabel NewAccUNLbl;
    private javax.swing.JPanel NewAccountPnl;
    private javax.swing.JButton PWCopyBtn;
    private javax.swing.JButton PasswordsBtn;
    private javax.swing.JPanel PasswordsPan;
    private javax.swing.JLabel PortunusLogo1;
    private javax.swing.JButton SQCopyBtn;
    private javax.swing.JButton SettingsBtn;
    private javax.swing.JPanel SettingsPan;
    private javax.swing.JButton ShowAccBtn;
    private javax.swing.JButton UNCopyBtn;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
