/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portunus;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author sgoug
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form MainScreenMockUp
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginScreen = new javax.swing.JPanel();
        LoginAccPan = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        LoginPgBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CreateNewAccBtn = new javax.swing.JButton();
        NewAccountScreen = new javax.swing.JPanel();
        NewAccPan = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        CreateAccBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NavigationScreen = new javax.swing.JPanel();
        BGPanel = new javax.swing.JPanel();
        NavMenu1 = new javax.swing.JPanel();
        PortunusLogo1 = new javax.swing.JLabel();
        PasswordsBtn = new javax.swing.JButton();
        SettingsBtn = new javax.swing.JButton();
        LoginOutBtn = new javax.swing.JButton();
        ChangingPanel = new javax.swing.JPanel();
        PasswordsPan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AccountList = new javax.swing.JList<>();
        AccDisplayPan = new javax.swing.JPanel();
        NewAccountPnl = new javax.swing.JPanel();
        NewAccNameField = new javax.swing.JTextField();
        NewAccNameLbl = new javax.swing.JLabel();
        NewAccUNField = new javax.swing.JTextField();
        NewAccUNLbl = new javax.swing.JLabel();
        NewAccPWField = new javax.swing.JTextField();
        NewAccPWLbl = new javax.swing.JLabel();
        AddAcountBtn = new javax.swing.JButton();
        NewAccSQLbl = new javax.swing.JLabel();
        NewAccSQField = new javax.swing.JTextField();
        ExistingAccountPnl = new javax.swing.JPanel();
        AccUNField = new javax.swing.JTextField();
        AccUNLbl = new javax.swing.JLabel();
        AccPWLbl = new javax.swing.JLabel();
        AccPWField = new javax.swing.JTextField();
        AccSQField1 = new javax.swing.JTextField();
        AccSQLbl1 = new javax.swing.JLabel();
        UNCopyBtn = new javax.swing.JButton();
        PWCopyBtn = new javax.swing.JButton();
        DeleteAccBtn = new javax.swing.JButton();
        EditAccbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SQAnserLbl1 = new javax.swing.JLabel();
        AccSQAnswerField1 = new javax.swing.JTextField();
        SQCopyBtn1 = new javax.swing.JButton();
        SQCopyBtn2 = new javax.swing.JButton();
        AccSQAnswerField2 = new javax.swing.JTextField();
        SQAnserLbl2 = new javax.swing.JLabel();
        AccSQField2 = new javax.swing.JTextField();
        AccSQLbl2 = new javax.swing.JLabel();
        AccSQLbl3 = new javax.swing.JLabel();
        AccSQField3 = new javax.swing.JTextField();
        SQAnserLbl3 = new javax.swing.JLabel();
        AccSQAnswerField3 = new javax.swing.JTextField();
        SQCopyBtn3 = new javax.swing.JButton();
        ShowAccBtn = new javax.swing.JButton();
        SettingsPan = new javax.swing.JPanel();
        colorPicker = new javax.swing.JColorChooser();
        ColorOptionsLabel = new javax.swing.JLabel();
        FontSizeLabel = new javax.swing.JLabel();
        FontSizeSelection = new javax.swing.JComboBox<>();
        SettingsDoneBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.CardLayout());

        LoginScreen.setBackground(new java.awt.Color(153, 153, 153));

        LoginAccPan.setBackground(new java.awt.Color(51, 204, 255));
        LoginAccPan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel3.setText("Password");

        LoginPgBtn.setBackground(new java.awt.Color(204, 204, 204));
        LoginPgBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        LoginPgBtn.setText("Login");
        LoginPgBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        LoginPgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPgBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel4.setText("Welcome to Portunus!");

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setText("Username");

        CreateNewAccBtn.setBackground(new java.awt.Color(153, 153, 153));
        CreateNewAccBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        CreateNewAccBtn.setText("Create New Account");
        CreateNewAccBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        CreateNewAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewAccBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginAccPanLayout = new javax.swing.GroupLayout(LoginAccPan);
        LoginAccPan.setLayout(LoginAccPanLayout);
        LoginAccPanLayout.setHorizontalGroup(
            LoginAccPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginAccPanLayout.createSequentialGroup()
                .addGroup(LoginAccPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginAccPanLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel4))
                    .addGroup(LoginAccPanLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(LoginAccPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LoginAccPanLayout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel5))
                            .addGroup(LoginAccPanLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(LoginPgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoginAccPanLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel3)))))
                .addGap(0, 57, Short.MAX_VALUE))
            .addGroup(LoginAccPanLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(CreateNewAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginAccPanLayout.setVerticalGroup(
            LoginAccPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginAccPanLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(LoginPgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(CreateNewAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LoginScreenLayout = new javax.swing.GroupLayout(LoginScreen);
        LoginScreen.setLayout(LoginScreenLayout);
        LoginScreenLayout.setHorizontalGroup(
            LoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginScreenLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(LoginAccPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        LoginScreenLayout.setVerticalGroup(
            LoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginScreenLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(LoginAccPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        getContentPane().add(LoginScreen, "card3");

        NewAccountScreen.setBackground(new java.awt.Color(153, 153, 153));

        NewAccPan.setBackground(new java.awt.Color(51, 204, 255));
        NewAccPan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPasswordField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setText("Password");

        CreateAccBtn.setBackground(new java.awt.Color(204, 204, 204));
        CreateAccBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        CreateAccBtn.setText("Create");
        CreateAccBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        CreateAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel7.setText("Welcome to Portunus!");

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setText("Username");

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel2.setText("Let's Create a New Account:");

        javax.swing.GroupLayout NewAccPanLayout = new javax.swing.GroupLayout(NewAccPan);
        NewAccPan.setLayout(NewAccPanLayout);
        NewAccPanLayout.setHorizontalGroup(
            NewAccPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewAccPanLayout.createSequentialGroup()
                .addGroup(NewAccPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewAccPanLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel6))
                    .addGroup(NewAccPanLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel7)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(NewAccPanLayout.createSequentialGroup()
                .addGroup(NewAccPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewAccPanLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(NewAccPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(NewAccPanLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel8))
                    .addGroup(NewAccPanLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(CreateAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NewAccPanLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        NewAccPanLayout.setVerticalGroup(
            NewAccPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewAccPanLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(CreateAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout NewAccountScreenLayout = new javax.swing.GroupLayout(NewAccountScreen);
        NewAccountScreen.setLayout(NewAccountScreenLayout);
        NewAccountScreenLayout.setHorizontalGroup(
            NewAccountScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewAccountScreenLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(NewAccPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        NewAccountScreenLayout.setVerticalGroup(
            NewAccountScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewAccountScreenLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(NewAccPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(446, Short.MAX_VALUE))
        );

        getContentPane().add(NewAccountScreen, "card4");

        NavigationScreen.setBackground(new java.awt.Color(153, 153, 153));
        NavigationScreen.setForeground(new java.awt.Color(153, 153, 153));
        NavigationScreen.setMaximumSize(new java.awt.Dimension(600, 900));

        BGPanel.setBackground(new java.awt.Color(153, 153, 153));

        NavMenu1.setBackground(new java.awt.Color(51, 204, 255));
        NavMenu1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        PortunusLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portunus/PortunusLogo15.png"))); // NOI18N

        PasswordsBtn.setBackground(new java.awt.Color(204, 204, 204));
        PasswordsBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        PasswordsBtn.setText("Passwords");
        PasswordsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        PasswordsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordsBtnActionPerformed(evt);
            }
        });

        SettingsBtn.setBackground(new java.awt.Color(204, 204, 204));
        SettingsBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        SettingsBtn.setText("Settings");
        SettingsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        SettingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsBtnActionPerformed(evt);
            }
        });

        LoginOutBtn.setBackground(new java.awt.Color(204, 204, 204));
        LoginOutBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        LoginOutBtn.setText("Log In/out");
        LoginOutBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        LoginOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavMenu1Layout = new javax.swing.GroupLayout(NavMenu1);
        NavMenu1.setLayout(NavMenu1Layout);
        NavMenu1Layout.setHorizontalGroup(
            NavMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavMenu1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(NavMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PasswordsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SettingsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoginOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PortunusLogo1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        NavMenu1Layout.setVerticalGroup(
            NavMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PortunusLogo1)
                .addGap(30, 30, 30)
                .addComponent(PasswordsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(SettingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(LoginOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ChangingPanel.setBackground(new java.awt.Color(153, 153, 153));
        ChangingPanel.setLayout(new java.awt.CardLayout());

        PasswordsPan.setBackground(new java.awt.Color(153, 153, 153));

        AccountList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        AccountList.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        AccountList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "New Account", "Existing Account" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        AccountList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(AccountList);

        AccDisplayPan.setBackground(new java.awt.Color(51, 204, 255));
        AccDisplayPan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        AccDisplayPan.setLayout(new java.awt.CardLayout());

        NewAccountPnl.setBackground(new java.awt.Color(51, 204, 255));
        NewAccountPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        NewAccNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        NewAccNameLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        NewAccNameLbl.setText("Account Name:");

        NewAccUNField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        NewAccUNLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        NewAccUNLbl.setText("Username:");

        NewAccPWField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        NewAccPWLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        NewAccPWLbl.setText("Password:");

        AddAcountBtn.setBackground(new java.awt.Color(204, 204, 204));
        AddAcountBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        AddAcountBtn.setText("Done!");
        AddAcountBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        NewAccSQLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        NewAccSQLbl.setText("Security Question:");

        NewAccSQField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout NewAccountPnlLayout = new javax.swing.GroupLayout(NewAccountPnl);
        NewAccountPnl.setLayout(NewAccountPnlLayout);
        NewAccountPnlLayout.setHorizontalGroup(
            NewAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewAccountPnlLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(NewAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewAccountPnlLayout.createSequentialGroup()
                        .addComponent(NewAccSQField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(AddAcountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NewAccountPnlLayout.createSequentialGroup()
                        .addGroup(NewAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewAccPWLbl)
                            .addGroup(NewAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NewAccUNLbl)
                                .addComponent(NewAccNameLbl)
                                .addComponent(NewAccNameField)
                                .addComponent(NewAccUNField)
                                .addComponent(NewAccPWField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NewAccSQLbl))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        NewAccountPnlLayout.setVerticalGroup(
            NewAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewAccountPnlLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(NewAccNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewAccNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NewAccUNLbl)
                .addGap(6, 6, 6)
                .addComponent(NewAccUNField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(NewAccPWLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewAccPWField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(NewAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewAccountPnlLayout.createSequentialGroup()
                        .addGap(51, 436, Short.MAX_VALUE)
                        .addComponent(AddAcountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewAccountPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NewAccSQLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NewAccSQField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        AccDisplayPan.add(NewAccountPnl, "card2");

        ExistingAccountPnl.setBackground(new java.awt.Color(51, 204, 255));
        ExistingAccountPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        AccUNField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        AccUNLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        AccUNLbl.setText("Username:");

        AccPWLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        AccPWLbl.setText("Password:");

        AccPWField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        AccSQField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        AccSQLbl1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        AccSQLbl1.setText("Security Question 1:");

        UNCopyBtn.setBackground(new java.awt.Color(204, 204, 204));
        UNCopyBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        UNCopyBtn.setText("Copy");
        UNCopyBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        PWCopyBtn.setBackground(new java.awt.Color(204, 204, 204));
        PWCopyBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        PWCopyBtn.setText("Copy");
        PWCopyBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        DeleteAccBtn.setBackground(new java.awt.Color(204, 204, 204));
        DeleteAccBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        DeleteAccBtn.setText("Delete");
        DeleteAccBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        EditAccbtn.setBackground(new java.awt.Color(204, 204, 204));
        EditAccbtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        EditAccbtn.setText("Edit");
        EditAccbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setText("Account Name");

        SQAnserLbl1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        SQAnserLbl1.setText("Answer:");

        AccSQAnswerField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        SQCopyBtn1.setBackground(new java.awt.Color(204, 204, 204));
        SQCopyBtn1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        SQCopyBtn1.setText("Copy");
        SQCopyBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        SQCopyBtn2.setBackground(new java.awt.Color(204, 204, 204));
        SQCopyBtn2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        SQCopyBtn2.setText("Copy");
        SQCopyBtn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        AccSQAnswerField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        SQAnserLbl2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        SQAnserLbl2.setText("Answer:");

        AccSQField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        AccSQLbl2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        AccSQLbl2.setText("Security Question 2:");

        AccSQLbl3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        AccSQLbl3.setText("Security Question 3:");

        AccSQField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        SQAnserLbl3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        SQAnserLbl3.setText("Answer:");

        AccSQAnswerField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        SQCopyBtn3.setBackground(new java.awt.Color(204, 204, 204));
        SQCopyBtn3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        SQCopyBtn3.setText("Copy");
        SQCopyBtn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout ExistingAccountPnlLayout = new javax.swing.GroupLayout(ExistingAccountPnl);
        ExistingAccountPnl.setLayout(ExistingAccountPnlLayout);
        ExistingAccountPnlLayout.setHorizontalGroup(
            ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                        .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                                .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                                        .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SQAnserLbl2)
                                            .addComponent(AccSQLbl2)
                                            .addComponent(AccSQAnswerField2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AccSQLbl3)
                                            .addComponent(AccSQAnswerField3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SQAnserLbl3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExistingAccountPnlLayout.createSequentialGroup()
                                        .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                                                .addComponent(AccSQLbl1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(UNCopyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                                    .addComponent(PWCopyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                                                .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(AccSQAnswerField1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(AccSQField2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(AccSQField3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                                .addComponent(SQCopyBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(SQCopyBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(SQCopyBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(61, 61, 61)))
                                .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DeleteAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditAccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                                .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AccPWLbl)
                                    .addComponent(AccUNLbl)
                                    .addComponent(AccUNField, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addComponent(AccPWField)
                                    .addComponent(AccSQField1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addGap(21, 21, 21))
                    .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                        .addComponent(SQAnserLbl1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        ExistingAccountPnlLayout.setVerticalGroup(
            ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(AccUNLbl))
                    .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UNCopyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AccUNField, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(AccPWLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccPWField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PWCopyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DeleteAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditAccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ExistingAccountPnlLayout.createSequentialGroup()
                        .addComponent(AccSQLbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccSQField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SQAnserLbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccSQAnswerField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SQCopyBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AccSQLbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccSQField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SQAnserLbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccSQAnswerField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SQCopyBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AccSQLbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccSQField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SQAnserLbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ExistingAccountPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccSQAnswerField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SQCopyBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );

        AccDisplayPan.add(ExistingAccountPnl, "card3");

        ShowAccBtn.setBackground(new java.awt.Color(204, 204, 204));
        ShowAccBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        ShowAccBtn.setText("Show");
        ShowAccBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        ShowAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAccBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PasswordsPanLayout = new javax.swing.GroupLayout(PasswordsPan);
        PasswordsPan.setLayout(PasswordsPanLayout);
        PasswordsPanLayout.setHorizontalGroup(
            PasswordsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordsPanLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PasswordsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PasswordsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(AccDisplayPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ShowAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        PasswordsPanLayout.setVerticalGroup(
            PasswordsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordsPanLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AccDisplayPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ChangingPanel.add(PasswordsPan, "card2");

        SettingsPan.setBackground(new java.awt.Color(153, 153, 153));

        colorPicker.setBackground(new java.awt.Color(51, 204, 255));
        colorPicker.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        colorPicker.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        colorPicker.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ColorOptionsLabel.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        ColorOptionsLabel.setText("Change Color:");

        FontSizeLabel.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        FontSizeLabel.setText("Font Size:");

        FontSizeSelection.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        FontSizeSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Extra Small", "Small", "Normal", "Large", "Extra Large" }));

        SettingsDoneBtn.setBackground(new java.awt.Color(204, 204, 204));
        SettingsDoneBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        SettingsDoneBtn.setText("Done");
        SettingsDoneBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        SettingsDoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsDoneBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SettingsPanLayout = new javax.swing.GroupLayout(SettingsPan);
        SettingsPan.setLayout(SettingsPanLayout);
        SettingsPanLayout.setHorizontalGroup(
            SettingsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsPanLayout.createSequentialGroup()
                .addGroup(SettingsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SettingsDoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SettingsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SettingsPanLayout.createSequentialGroup()
                            .addGap(158, 158, 158)
                            .addComponent(ColorOptionsLabel))
                        .addGroup(SettingsPanLayout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addGroup(SettingsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(colorPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(SettingsPanLayout.createSequentialGroup()
                                    .addGap(61, 61, 61)
                                    .addComponent(FontSizeLabel))
                                .addComponent(FontSizeSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        SettingsPanLayout.setVerticalGroup(
            SettingsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingsPanLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ColorOptionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(FontSizeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FontSizeSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(SettingsDoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        ChangingPanel.add(SettingsPan, "card3");

        javax.swing.GroupLayout BGPanelLayout = new javax.swing.GroupLayout(BGPanel);
        BGPanel.setLayout(BGPanelLayout);
        BGPanelLayout.setHorizontalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NavMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChangingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BGPanelLayout.setVerticalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NavMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChangingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout NavigationScreenLayout = new javax.swing.GroupLayout(NavigationScreen);
        NavigationScreen.setLayout(NavigationScreenLayout);
        NavigationScreenLayout.setHorizontalGroup(
            NavigationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationScreenLayout.createSequentialGroup()
                .addComponent(BGPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        NavigationScreenLayout.setVerticalGroup(
            NavigationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(NavigationScreen, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordsBtnActionPerformed
        PasswordsPan.setVisible(true);
        SettingsPan.setVisible(false);
    }//GEN-LAST:event_PasswordsBtnActionPerformed

    private void SettingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsBtnActionPerformed
        SettingsPan.setVisible(true);
        PasswordsPan.setVisible(false);
    }//GEN-LAST:event_SettingsBtnActionPerformed

    private void LoginPgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPgBtnActionPerformed
        //right now it will automatically display the Navigation screen when clicked
        //needs to be changed to only work when the right password is entered
        NavigationScreen.setVisible(true);
        LoginScreen.setVisible(false);
        NewAccountScreen.setVisible(false);
    }//GEN-LAST:event_LoginPgBtnActionPerformed

    private void LoginOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginOutBtnActionPerformed
        LoginScreen.setVisible(true);
        NavigationScreen.setVisible(false);
        NewAccountScreen.setVisible(false);
    }//GEN-LAST:event_LoginOutBtnActionPerformed

    private void CreateAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccBtnActionPerformed
        NavigationScreen.setVisible(true);
        LoginScreen.setVisible(false);
        NewAccountScreen.setVisible(false);
    }//GEN-LAST:event_CreateAccBtnActionPerformed

    private void CreateNewAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewAccBtnActionPerformed
        NewAccountScreen.setVisible(true);
        NavigationScreen.setVisible(false);
        LoginScreen.setVisible(false);
    }//GEN-LAST:event_CreateNewAccBtnActionPerformed

    private void SettingsDoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsDoneBtnActionPerformed
        // changing the color
        Color interfaceColor;
        interfaceColor = colorPicker.getColor();
        NavMenu1.setBackground(interfaceColor);
        NewAccountPnl.setBackground(interfaceColor);
        ExistingAccountPnl.setBackground(interfaceColor);
        LoginAccPan.setBackground(interfaceColor);
        NewAccPan.setBackground(interfaceColor);
        
        //changing the font size
        if(FontSizeSelection.getSelectedItem() == "Extra Small") {
            FontSizeLabel.setFont(new Font("Agency FB", Font.BOLD, 12));
        }
        if(FontSizeSelection.getSelectedItem() == "Small") {
            FontSizeLabel.setFont(new Font("Agency FB", Font.BOLD, 16));
        }
        if(FontSizeSelection.getSelectedItem() == "Normal") {
            FontSizeLabel.setFont(new Font("Agency FB", Font.BOLD, 24));
        }
        if(FontSizeSelection.getSelectedItem() == "Large") {
            FontSizeLabel.setFont(new Font("Agency FB", Font.BOLD, 30));
        }
        if(FontSizeSelection.getSelectedItem() == "Extra Large") {
            FontSizeLabel.setFont(new Font("Agency FB", Font.BOLD, 40));
        }
    }//GEN-LAST:event_SettingsDoneBtnActionPerformed

    private void ShowAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAccBtnActionPerformed
        if(AccountList.getSelectedValue().equals("New Account")) {
            NewAccountPnl.setVisible(true);
            ExistingAccountPnl.setVisible(false);
        }
        if(AccountList.getSelectedValue().equals("Exisitng Account")) {
            ExistingAccountPnl.setVisible(true);
            NewAccountPnl.setVisible(false);
        }
    }//GEN-LAST:event_ShowAccBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccDisplayPan;
    private javax.swing.JTextField AccPWField;
    private javax.swing.JLabel AccPWLbl;
    private javax.swing.JTextField AccSQAnswerField1;
    private javax.swing.JTextField AccSQAnswerField2;
    private javax.swing.JTextField AccSQAnswerField3;
    private javax.swing.JTextField AccSQField1;
    private javax.swing.JTextField AccSQField2;
    private javax.swing.JTextField AccSQField3;
    private javax.swing.JLabel AccSQLbl1;
    private javax.swing.JLabel AccSQLbl2;
    private javax.swing.JLabel AccSQLbl3;
    private javax.swing.JTextField AccUNField;
    private javax.swing.JLabel AccUNLbl;
    private javax.swing.JList<String> AccountList;
    private javax.swing.JButton AddAcountBtn;
    private javax.swing.JPanel BGPanel;
    private javax.swing.JPanel ChangingPanel;
    private javax.swing.JLabel ColorOptionsLabel;
    private javax.swing.JButton CreateAccBtn;
    private javax.swing.JButton CreateNewAccBtn;
    private javax.swing.JButton DeleteAccBtn;
    private javax.swing.JButton EditAccbtn;
    private javax.swing.JPanel ExistingAccountPnl;
    private javax.swing.JLabel FontSizeLabel;
    private javax.swing.JComboBox<String> FontSizeSelection;
    private javax.swing.JPanel LoginAccPan;
    private javax.swing.JButton LoginOutBtn;
    private javax.swing.JButton LoginPgBtn;
    private javax.swing.JPanel LoginScreen;
    private javax.swing.JPanel NavMenu1;
    private javax.swing.JPanel NavigationScreen;
    private javax.swing.JTextField NewAccNameField;
    private javax.swing.JLabel NewAccNameLbl;
    private javax.swing.JTextField NewAccPWField;
    private javax.swing.JLabel NewAccPWLbl;
    private javax.swing.JPanel NewAccPan;
    private javax.swing.JTextField NewAccSQField;
    private javax.swing.JLabel NewAccSQLbl;
    private javax.swing.JTextField NewAccUNField;
    private javax.swing.JLabel NewAccUNLbl;
    private javax.swing.JPanel NewAccountPnl;
    private javax.swing.JPanel NewAccountScreen;
    private javax.swing.JButton PWCopyBtn;
    private javax.swing.JButton PasswordsBtn;
    private javax.swing.JPanel PasswordsPan;
    private javax.swing.JLabel PortunusLogo1;
    private javax.swing.JLabel SQAnserLbl1;
    private javax.swing.JLabel SQAnserLbl2;
    private javax.swing.JLabel SQAnserLbl3;
    private javax.swing.JButton SQCopyBtn1;
    private javax.swing.JButton SQCopyBtn2;
    private javax.swing.JButton SQCopyBtn3;
    private javax.swing.JButton SettingsBtn;
    private javax.swing.JButton SettingsDoneBtn;
    private javax.swing.JPanel SettingsPan;
    private javax.swing.JButton ShowAccBtn;
    private javax.swing.JButton UNCopyBtn;
    private javax.swing.JColorChooser colorPicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
